// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CYauXgM-OSSfVVzFoCA005wtYt6RXWc',
    appId: '1:384224797890:web:bcd1ed7e03388f6290c75b',
    messagingSenderId: '384224797890',
    projectId: 'smart-pharmacy-app-280c7',
    authDomain: 'smart-pharmacy-app-280c7.firebaseapp.com',
    databaseURL: 'https://smart-pharmacy-app-280c7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pharmacy-app-280c7.firebasestorage.app',
    measurementId: 'G-8DBRMJ90HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6UP7qPe0q7AkicVW8xIEUlbeh8QH0DA',
    appId: '1:384224797890:android:bea8452bf433b0f590c75b',
    messagingSenderId: '384224797890',
    projectId: 'smart-pharmacy-app-280c7',
    databaseURL: 'https://smart-pharmacy-app-280c7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pharmacy-app-280c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKDrbrWi1_VHJMfJyKm2a3QofbZYd9fc',
    appId: '1:384224797890:ios:9451e59c38db634690c75b',
    messagingSenderId: '384224797890',
    projectId: 'smart-pharmacy-app-280c7',
    databaseURL: 'https://smart-pharmacy-app-280c7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-pharmacy-app-280c7.firebasestorage.app',
    iosBundleId: 'com.example.smartPharmacyApp',
  );
}
