import 'package:flutter/material.dart';
import '../constants/colors.dart';
import '../constants/styles.dart';
import '../widgets/custom_button.dart';

class AccountCreated extends StatelessWidget {
  const AccountCreated({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Image.asset(
                'assets/images/Sammylinesuccess.png',
                width: 256,
                height: 256,
              ),
              const SizedBox(height: 30),
              Text(
                'تم إنشاء حسابك بنجاح',
                style: AppTextStyles.header.copyWith(color: AppColors.textDark),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              Text(
                'مرحبًا بك في وجهتك للصيدلية، تم إنشاء حسابك.',
                style: AppTextStyles.bodySmall,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 50),
              CustomButton(
                text: 'المتابعة',
                onPressed: () => Navigator.pushNamed(context, '/home'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// import 'package:flutter/material.dart';
//
// void main() {
//   runApp(const FigmaToCodeApp());
// }
//
// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(body: ListView(children: [AccountCreated()])),
//     );
//   }
// }
//
// class AccountCreated extends StatelessWidget {
//   const AccountCreated({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 393,
//           height: 852,
//           clipBehavior: Clip.antiAlias,
//           decoration: BoxDecoration(color: Colors.white),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 83.54,
//                 top: 422,
//                 child: Text(
//                   'تم إنشاء حسابك بنجاح',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 25,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 68.84,
//                 top: 498,
//                 child: Text(
//                   'مرحبًا بك في وجهتك للصيدلية، تم إنشاء حسابك.',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: const Color(0xFFA09393),
//                     fontSize: 14,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 26,
//                 top: 552,
//                 child: Container(
//                   width: 342,
//                   height: 56,
//                   decoration: ShapeDecoration(
//                     color: const Color(0xFF00676C),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(13),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 166,
//                 top: 568,
//                 child: Text(
//                   'المتابعة',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 20,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 69,
//                 top: 131,
//                 child: Container(
//                   width: 256,
//                   height: 256,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/256x256"),
//                       fit: BoxFit.cover,
//                     ),
//                     border: Border.all(width: 1),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }
