import 'package:flutter/material.dart';
import '../constants/colors.dart';
import '../constants/styles.dart';
import '../widgets/custom_button.dart';

class VerifyEmailScreen extends StatelessWidget {
  const VerifyEmailScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Image.network(
                'https://via.placeholder.com/256',
                width: 256,
                height: 256,
              ),
              const SizedBox(height: 30),
              Text(
                'تحقق من عنوان بريدك الإلكتروني',
                style: AppTextStyles.header.copyWith(color: AppColors.textDark),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              Text('example@gmail.com', style: AppTextStyles.bodyLarge),
              const SizedBox(height: 20),
              Text(
                'تهانينا! حسابك في انتظارك ,\n قم بالتحقق من وجود بريدك الإلكتروني لبدء التسوق والاستمتاع.',
                style: AppTextStyles.bodySmall,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 50),
              CustomButton(
                text: 'المتابعة',
                onPressed: () => Navigator.pushNamed(context, '/home'),
              ),
              const SizedBox(height: 20),
              TextButton(
                onPressed: () {},
                child: Text(
                  'إعادة إرسال البريد الإلكتروني',
                  style: AppTextStyles.bodyMedium.copyWith(
                    color: AppColors.primary,
                    decoration: TextDecoration.underline,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// class VerifyEmailScreen extends StatelessWidget {
//   const VerifyEmailScreen({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: AppColors.background,
//       body: Center(
//         child: Padding(
//           padding: const EdgeInsets.all(20),
//           child: Column(
//             mainAxisAlignment: MainAxisAlignment.center,
//             children: [
//               Image.network(
//                 'https://via.placeholder.com/256',
//                 width: 256,
//                 height: 256,
//               ),
//               const SizedBox(height: 30),
//               Text(
//                 'تحقق من عنوان بريدك الإلكتروني',
//                 style: AppTextStyles.header.copyWith(color: AppColors.textDark),
//                 textAlign: TextAlign.center,
//               ),
//               const SizedBox(height: 10),
//               Text(
//                 'example@gmail.com',
//                 style: AppTextStyles.bodyLarge,
//               ),
//               const SizedBox(height: 20),
//               Text(
//                 'تهانينا! حسابك في انتظارك,\nقم بالتحقق من وجود بريدك الإلكتروني لبدء التسوق والاستمتاع.',
//                 style: AppTextStyles.bodySmall,
//                 textAlign: TextAlign.center,
//               ),
//               const SizedBox(height: 50),
//               CustomButton(
//                 text: 'المتابعة',
//                 onPressed: () => Navigator.pushNamed(context, '/home'),
//               ),
//               const SizedBox(height: 20),
//               TextButton(
//                 onPressed: () {},
//                 child: Text(
//                   'إعادة إرسال البريد الإلكتروني',
//                   style: AppTextStyles.bodyMedium.copyWith(
//                     color: AppColors.primary,
//                     decoration: TextDecoration.underline,
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }

// import 'package:flutter/material.dart';
//
// void main() {
//   runApp(const FigmaToCodeApp());
// }
//
// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(body: ListView(children: [VerifyEmail()])),
//     );
//   }
// }
//
// class VerifyEmail extends StatelessWidget {
//   const VerifyEmail({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 393,
//           height: 852,
//           clipBehavior: Clip.antiAlias,
//           decoration: BoxDecoration(color: Colors.white),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 41,
//                 top: 422,
//                 child: Text(
//                   'تحقق من عنوان بريدك الإلكتروني',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 25,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 114,
//                 top: 466,
//                 child: Text(
//                   'example@gmail.com',
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 18,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 17,
//                 top: 502,
//                 child: Text(
//                   'تهانينا! حسابك في انتظارك ,\n قم بالتحقق من وجود بريدك الإلكتروني لبدء التسوق والاستمتاع.',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: const Color(0xFFA09393),
//                     fontSize: 14,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 26,
//                 top: 552,
//                 child: Container(
//                   width: 342,
//                   height: 56,
//                   decoration: ShapeDecoration(
//                     color: const Color(0xFF00676C),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.circular(13),
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 160,
//                 top: 568,
//                 child: Text(
//                   'المتابعة',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: Colors.white,
//                     fontSize: 20,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 116,
//                 top: 623,
//                 child: Text(
//                   'إعادة إرسال البريد الإلكتروني',
//                   textAlign: TextAlign.right,
//                   style: TextStyle(
//                     color: const Color(0xFF00676C),
//                     fontSize: 16,
//                     fontFamily: 'Inter',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 69,
//                 top: 107,
//                 child: Container(
//                   width: 256,
//                   height: 256,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/256x256"),
//                       fit: BoxFit.cover,
//                     ),
//                     border: Border.all(width: 1),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }
